{% set name = "plumbum" %}
{% set version = "1.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e6dc032f4af952665f32f3206567bc23b7858b1413611afe603a3f8ad9bfd75

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - hatchling
    - hatch-vcs
  run:
    - python >=3.6
    - pywin32-on-windows
    - paramiko

test:
  imports:
    - plumbum
    - plumbum.cli
    - plumbum.cli.image
    - plumbum.colorlib
    - plumbum.commands
    - plumbum.fs
    - plumbum.machines
    - plumbum.path
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plumbum.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'Plumbum: shell combinators library'

  description: |
    Apart from shell-like syntax and handy shortcuts, the library provides local and
    remote command execution (over SSH), local and remote file-system paths, easy
    working-directory and environment manipulation, a programmatic Command-Line
    Interface (CLI) application toolkit, and a color library.
  doc_url: https://plumbum.readthedocs.io/
  dev_url: https://github.com/tomerfiliba/plumbum

extra:
  recipe-maintainers:
    - henryiii
