{% set name = "plumbum" %}
{% set version = "1.6.5" %}
{% set sha256 = "d8abb059bb62beb6c99db08d3598167abaeeab53eaf218f91e74bae471a24bee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - paramiko

test:
  imports:
    - plumbum
    - plumbum.cli
    - plumbum.cli.image
    - plumbum.colorlib
    - plumbum.commands
    - plumbum.fs
    - plumbum.machines
    - plumbum.path

about:
  home: https://plumbum.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'Plumbum: shell combinators library'

  description: |
    Apart from shell-like syntax and handy shortcuts, the library provides local and
    remote command execution (over SSH), local and remote file-system paths, easy
    working-directory and environment manipulation, a programmatic Command-Line
    Interface (CLI) application toolkit, and a color library.
  doc_url: https://plumbum.readthedocs.io/
  dev_url: https://github.com/tomerfiliba/plumbum

extra:
  recipe-maintainers:
    - henryiii
