{% set name = "plumbum" %}
{% set version = "1.6.6" %}
{% set sha256 = "d179b90a9927f91427a28c1bac2864c61342cb43ef39aa7324c7c9a96bcc23eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - setuptools
    - paramiko

test:
  imports:
    - plumbum
    - plumbum.cli
    - plumbum.cli.image
    - plumbum.colorlib
    - plumbum.commands
    - plumbum.fs
    - plumbum.machines
    - plumbum.path

about:
  home: https://plumbum.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'Plumbum: shell combinators library'

  description: |
    Apart from shell-like syntax and handy shortcuts, the library provides local and
    remote command execution (over SSH), local and remote file-system paths, easy
    working-directory and environment manipulation, a programmatic Command-Line
    Interface (CLI) application toolkit, and a color library.
  doc_url: https://plumbum.readthedocs.io/
  dev_url: https://github.com/tomerfiliba/plumbum

extra:
  recipe-maintainers:
    - henryiii
