{% set name = "plumbum" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f1da1f167a2afe731a85de3f56810f424926c0a1a8fd1999ceb2ef20b618246d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools_scm >=3.4.3
    - setuptools >=42
  run:
    - python >=2.7
    - pywin32-on-windows
    - paramiko

test:
  imports:
    - plumbum
    - plumbum.cli
    - plumbum.cli.image
    - plumbum.colorlib
    - plumbum.commands
    - plumbum.fs
    - plumbum.machines
    - plumbum.path
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://plumbum.readthedocs.io
  license: MIT
  license_file: LICENSE
  summary: 'Plumbum: shell combinators library'

  description: |
    Apart from shell-like syntax and handy shortcuts, the library provides local and
    remote command execution (over SSH), local and remote file-system paths, easy
    working-directory and environment manipulation, a programmatic Command-Line
    Interface (CLI) application toolkit, and a color library.
  doc_url: https://plumbum.readthedocs.io/
  dev_url: https://github.com/tomerfiliba/plumbum

extra:
  recipe-maintainers:
    - henryiii
