schema_version: 1

context:
  version: 1.9.0

package:
  name: plumbum
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/plumbum/plumbum-${{ version }}.tar.gz
  sha256: e640062b72642c3873bd5bdc3effed75ba4d3c70ef6b6a7b907357a84d909219

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - pywin32-on-windows
    - paramiko
    - importlib_resources

tests:
  - python:
      imports:
        - plumbum
        - plumbum.cli
        - plumbum.cli.image
        - plumbum.colorlib
        - plumbum.commands
        - plumbum.fs
        - plumbum.machines
        - plumbum.path
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  license: MIT
  license_file: LICENSE
  summary: |
    Plumbum: shell combinators library

  description: |
    Apart from shell-like syntax and handy shortcuts, the library provides local and
    remote command execution (over SSH), local and remote file-system paths, easy
    working-directory and environment manipulation, a programmatic Command-Line
    Interface (CLI) application toolkit, and a color library.
  homepage: https://plumbum.readthedocs.io
  repository: https://github.com/tomerfiliba/plumbum
  documentation: https://plumbum.readthedocs.io/

extra:
  recipe-maintainers:
    - henryiii
